<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \App\Entity\Company implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'industry', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'employees_count_range', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'postal_code', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'website_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'linkedin_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'facebook_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'twitter_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'youtube_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'contact_phone', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'contact_email', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'advertisements'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'industry', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'employees_count_range', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'postal_code', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'website_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'linkedin_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'facebook_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'twitter_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'youtube_link', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'contact_phone', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'contact_email', '' . "\0" . 'App\\Entity\\Company' . "\0" . 'advertisements'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Company $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?\App\Entity\CompanyType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?\App\Entity\CompanyType $type): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndustry(): ?\App\Entity\CompanyIndustry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndustry', []);

        return parent::getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndustry(?\App\Entity\CompanyIndustry $industry): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndustry', [$industry]);

        return parent::setIndustry($industry);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeesCountRange(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeesCountRange', []);

        return parent::getEmployeesCountRange();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeesCountRange(string $employees_count_range): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeesCountRange', [$employees_count_range]);

        return parent::setEmployeesCountRange($employees_count_range);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(string $city): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(string $country): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $address): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode(string $postal_code): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postal_code]);

        return parent::setPostalCode($postal_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsiteLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsiteLink', []);

        return parent::getWebsiteLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsiteLink(string $website_link): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsiteLink', [$website_link]);

        return parent::setWebsiteLink($website_link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedinLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedinLink', []);

        return parent::getLinkedinLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkedinLink(string $linkedin_link): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedinLink', [$linkedin_link]);

        return parent::setLinkedinLink($linkedin_link);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookLink', []);

        return parent::getFacebookLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookLink(string $facebook_link): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookLink', [$facebook_link]);

        return parent::setFacebookLink($facebook_link);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterLink', []);

        return parent::getTwitterLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterLink(string $twitter_link): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterLink', [$twitter_link]);

        return parent::setTwitterLink($twitter_link);
    }

    /**
     * {@inheritDoc}
     */
    public function getYoutubeLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYoutubeLink', []);

        return parent::getYoutubeLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setYoutubeLink(string $youtube_link): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYoutubeLink', [$youtube_link]);

        return parent::setYoutubeLink($youtube_link);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPhone', []);

        return parent::getContactPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPhone(string $contact_phone): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPhone', [$contact_phone]);

        return parent::setContactPhone($contact_phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactEmail', []);

        return parent::getContactEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactEmail(string $contact_email): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactEmail', [$contact_email]);

        return parent::setContactEmail($contact_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdvertisements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdvertisements', []);

        return parent::getAdvertisements();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdvertisement(\App\Entity\Advertisement $advertisement): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdvertisement', [$advertisement]);

        return parent::addAdvertisement($advertisement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdvertisement(\App\Entity\Advertisement $advertisement): \App\Entity\Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdvertisement', [$advertisement]);

        return parent::removeAdvertisement($advertisement);
    }

}
